[package]
name = "rustPhoton"
version = "0.1.0"
edition = "2021"

[lib]
name = "boson"
path = "src/core/mod.rs"

[[bin]]
name = "apitests"
path = "tests/apitests/mod.rs"

[[bin]]
name = "shell"
path = "apps/shell/main.rs"

[dependencies]
hex = "0.4"
