[package]
name = "rustPhoton"
version = "0.1.0"
edition = "2021"

[lib]
name = "boson"
path = "src/core/id.rs"

[[bin]]
name = "apitests"
path = "tests/apitests/id_tests.rs"

[[bin]]
name = "shell"
path = "apps/shell/main.rs"

[dependencies]
